# black formatter
# Ref: https://black.readthedocs.io/en/stable/usage_and_configuration/index.html

[tool.black]
required-version = "23.9.1"
target-version = "${{package.python_versions_py3x}}"
line-length = "${{package.dev_config.max_line_length}}"
verbose = true
