coverage:
  precision: 2
  round: nearest
  range: 90...100
  status:
    project:
      default:
        target: 100%
        threshold: 5%
comment:
  layout: header, diff, flags, files
  require_changes: false
  behavior: default
