title: '[General] '
labels:
- General Introduction
body:
- type: markdown
  attributes:
    value: "This is text that will show up in the template!\n"
- type: textarea
  id: improvements
  attributes:
    label: Top 3 improvements
    description: What are the top 3 improvements we could make to this project?
    value: "1.\n2.\n3.\n...\n"
    render: bash
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Markdown header\nAnd some more markdown\n"
- type: input
  id: has-id
  attributes:
    label: Suggestions
    description: A description about suggestions to help you
  validations:
    required: true
- type: dropdown
  id: download
  attributes:
    label: Which area of this project could be most improved?
    options:
    - Documentation
    - Pull request review time
    - Bug fix time
    - Release cadence
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Check that box!
    options:
    - label: This one!
      required: true
    - label: I won't stop you if you check this one, too
- type: markdown
  attributes:
    value: "### The thrilling conclusion\n_to our template_\n"
