# Conda environment used for building the website

name: docs_env
channels: [ conda-forge, defaults ]
dependencies:
  - python
  - pip

  # Sphinx website and documentation generator.
  #
  # References
  # ----------
  # - Repository: https://github.com/sphinx-doc/sphinx
  # - Conda-forge: https://anaconda.org/conda-forge/sphinx
  - sphinx = 7.2.6

  # Sphinx website theme.
  #
  # References
  # ----------
  # - Repository: https://github.com/pydata/pydata-sphinx-theme
  # - Documentation: https://pydata-sphinx-theme.readthedocs.io/en/v0.14.3/
  # - Conda-forge: https://anaconda.org/conda-forge/pydata-sphinx-theme
  - pydata-sphinx-theme = 0.14.3

  # Sphinx extension allowing for the use MyST Markdown syntax.
  #
  # References
  # ----------
  # - Repository: https://github.com/executablebooks/MyST-Parser
  # - Documentation: https://myst-parser.readthedocs.io/en/v2.0.0/
  # - Conda-forge: https://anaconda.org/conda-forge/myst-parser
  - myst-parser = 2.0.0

  # Sphinx extension for adding responsive web components, such as grids, cards, tabs, etc.
  #
  # References
  # ----------
  # - Repository: https://github.com/executablebooks/sphinx-design
  # - Documentation: https://sphinx-design.readthedocs.io/en/stable/
  # - Conda-forge: https://anaconda.org/conda-forge/sphinx-design
  - sphinx-design = 0.5.0

  # Sphinx extension for adding a blog to the website.
  #
  # References
  # ----------
  # - Repository: https://github.com/sunpy/ablog
  # - Documentation: https://ablog.readthedocs.io/en/v0.11.6/
  # - Conda-forge: https://anaconda.org/conda-forge/ablog
  - ablog = 0.11.6

  # Sphinx extension for generating OpenGraph metadata for each page of the documentation.
  #
  # References
  # ----------
  # - Repository: https://github.com/wpilibsuite/sphinxext-opengraph
  # - Documentation: https://sphinxext-opengraph.readthedocs.io/en/latest/
  # - Conda-forge: https://anaconda.org/conda-forge/sphinxext-opengraph
  - sphinxext-opengraph = 0.9.0

  # Sphinx extension for BibTeX-style citations.
  #
  # References
  # ----------
  # - Repository: https://github.com/mcmtroffaes/sphinxcontrib-bibtex
  # - Documentation: https://sphinxcontrib-bibtex.readthedocs.io/en/v2.5.0/
  # - Conda-forge: https://anaconda.org/conda-forge/sphinxcontrib-bibtex
  - sphinxcontrib-bibtex = 2.6.1

  # Sphinx extension for including Mermaid diagrams and charts in the documentation.
  #
  # References
  # ----------
  # - Repository: https://github.com/mgaitan/sphinxcontrib-mermaid
  # - Documentation: https://sphinxcontrib-mermaid-demo.readthedocs.io/en/stable/
  # - Conda-forge: https://anaconda.org/conda-forge/sphinxcontrib-mermaid
  - sphinxcontrib-mermaid = 0.9.2

  # Sphinx extension for adding a "Copy" button to code blocks.
  # References
  # ----------
  # - Repository: https://github.com/executablebooks/sphinx-copybutton
  # - Documentation: https://sphinx-copybutton.readthedocs.io/en/stable/
  # - Conda-forge: https://anaconda.org/conda-forge/sphinx-copybutton
  - sphinx-copybutton = 0.5.2

  # Library for rendering SVG files and using them in PDF (via LaTeX) builds done by latexmk.
  #
  # References
  # ----------
  # - Repository: https://gitlab.gnome.org/GNOME/librsvg
  # - Documentation: https://wiki.gnome.org/Projects/LibRsvg
  # - Conda-forge: https://anaconda.org/conda-forge/librsvg
  - librsvg

  # Pip-only dependencies
  - pip:
    - sphinx-last-updated-by-git
    - sphinxcontrib-svg2pdfconverter
