name:  🖥 App 🐞 Bug Report 📱 API
description: Report a problem (e.g. errors and unexpected results) encountered while
  using the application's Python API.
labels:
- 'Type: patch-release'
- 'SubType: api'
- 'Status: triage'
assignees:
- repodynamics
body:
- type: markdown
  attributes:
    value: "<p align=\"justify\">\n  Thank you for taking the time to report a problem
      in PyPackIT;\n  we greatly appreciate your contribution! ❤️🙏\n</p>\n<h2>Terms
      and Conditions</h2>\n<p align=\"justify\">\n  Before submitting a report, please
      take a moment to review and accept our terms and conditions;\n  they will help
      us process the issue as fast as possible,\n  and not bother you with additional
      questions.\n</p>\n<h3>⛔ Choosing the right form</h3>\n<ul>\n  <li>\n    <p align=\"\
      justify\">\n      Please note that this form is specifically for reporting a
      <b>non-security-related bug</b>\n      in the PyPackIT API, i.e. an unexpected
      behavior that occurs while using the application\n      as an import package.\n\
      \    </p>\n  </li>\n  <li>\n    <p align=\"justify\">\n      To 🚨 <a href=\"\
      https://github.com/RepoDynamics/PyPackIT/security\"><b>report a security vulnerability</b></a>\n\
      \      🚨 please first read our\n      <a href=\"https://github.com/RepoDynamics/PyPackIT/security/policy\"\
      >security policy</a>, and fill a\n      <a href=\"https://github.com/RepoDynamics/PyPackIT/security/advisories/new\"\
      >private security advisory form</a> instead.\n    </p>\n  </li>\n  <li>\n  \
      \  <p align=\"justify\">\n      For other types of issues, such as problems
      in the\n      <a href=\"${{url.github.issues.new.app_bug_setup]}\">installation
      process</a>,\n      <a href=\"${{url.github.issues.new.docs_bug_site]}\">website</a>,
      or\n      <a href=\"${{url.github.issues.new.docs_bug_content]}\">documentation</a>,\n\
      \      or for requesting new features and enhancements, please select the appropriate
      form\n      from the <a href=\"${{url.github.issues.template_chooser]}\">issue
      template chooser</a>.\n    </p>\n  </li>\n</ul>\n<blockquote>\n  💡 <a href=\"\
      https://pypackit.repodynamics.com/help/contact\"><b>Contact us</b></a>\n  <br>\n\
      \  <p align=\"justify\">\n    Can't find the right form or unsure about which
      one to choose?\n    Ask a question and get help in the\n    <a href=\"https://github.com/RepoDynamics/PyPackIT/discussions/new?category=question_issues\"\
      >discussion forum</a>.\n  </p>\n</blockquote>\n<h3>⚠️ Verifying the bug</h3>\n
      Before submitting a report, please make sure that you are following our <a href=\"\
      https://pypackit.repodynamics.com/contribute/feedback/report\">Bug Report Guidelines</a>
      to verify that: <ol>\n  <li>\n    The issue you are experiencing is in fact
      a bug, and not a documented expected behavior.\n  </li>\n  <li>\n    The bug
      is reproducible in the latest version of the release, and has not yet been reported.\n\
      \  </li>\n</ol>\n<blockquote>\n    💡 <a href=\"https://github.com/RepoDynamics/PyPackIT/discussions/new?category=question_issues\"\
      ><b>Open a discussion instead!</b></a>\n    <br>\n    This verification process
      is non-trivial, and can be time-consuming.\n    If you are not a collaborator
      and don't have the time to go through the process,\n    you can always open
      a discussion instead; we will investigate the problem as soon as possible,\n\
      \    and convert the discussion into an issue if the bug is verified.\n</blockquote>\n
      <h3>🤝 Code of conduct</h3>\n<p align=\"justify\">\n  Please make sure that you
      are following our\n  <a href=\"https://github.com/RepoDynamics/PyPackIT/blob/main/CODE_OF_CONDUCT.md\"\
      >Code of Conduct</a>,\n  so that we can process the issue as soon as possible.\n\
      </p>\n<h3>✅ Agreements</h3>"
- type: checkboxes
  id: terms
  attributes:
    label: 'To submit an issue, please agree to the following terms and conditions:'
    options:
    - label: I have read the [Contributing Guidelines](https://github.com/RepoDynamics/PyPackIT/blob/main/CONTRIBUTING.md)
        and am following the [Bug Report Guidelines](https://pypackit.repodynamics.com/contribute/feedback/report).
      required: true
    - label: I have read, understood, and agree to follow the [Code of Conduct](https://github.com/RepoDynamics/PyPackIT/blob/main/CODE_OF_CONDUCT.md).
      required: true
- type: markdown
  attributes:
    value: <h3>🧑‍💻 Collaborate</h3>
- type: checkboxes
  id: collab
  attributes:
    label: "Thank you again for filling this bug report.\nIf you are willing to collaborate
      on fixing the issue, please select the option below.\n"
    options:
    - label: I am willing to work on the issue and submit a pull request.
      required: false
- type: markdown
  attributes:
    value: <br><h2>System and Version Specifications</h2>
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: "Which operating systems have you tested?\nPlease select all options
      where you have encountered the bug.\n"
    multiple: true
    options:
    - Linux
    - Windows
    - macOS
  validations:
    required: true
- type: dropdown
  id: python_version
  attributes:
    label: Python Version
    description: "Which Python versions have you tested?\nPlease select all versions
      where you have encountered the bug.\n"
    multiple: true
    options:
    - '3.10'
    - '3.11'
    - '3.12'
  validations:
    required: true
- type: dropdown
  id: package_manager
  attributes:
    label: Package Manager
    description: "Which package manager have you used to download and install the
      package?\n"
    multiple: false
    options:
    - conda
    - pip
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Package Version
    description: "Which versions of our software are affected?\nPlease select all
      versions where you have encountered the bug.\n"
    multiple: true
    options:
    - 0.0.0
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: "Please provide the details of all installed packages and their exact
      versions in the environment where you have encountered the bug. Follow the instructions
      below based on the package manager you have selected:\n1. **`pip`**: Run `pip
      freeze > requirements.txt` in your terminal within the environment, and copy
      the contents of the generated `requirements.txt` file here.\n2. **`conda`**:
      Run `conda env export > environment.yml` in your terminal within the environment
      (or alternatively `conda env export -n {YOUR_ENVIRONMENT_NAME} > environment.yml`),
      and copy the contents of the generated `environment.yml` file here."
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>\n<h2>Bug Report</h2>\n"
- type: input
  id: api_entry
  attributes:
    label: Fully Qualified Name
    description: "Please provide the fully qualified name of the API endpoint that
      is causing the problem.\n"
    value: pypackit.
  validations:
    required: true
- type: textarea
  id: summary
  attributes:
    label: Summary
    description: Please provide a brief summary of the bug.
  validations:
    required: true
- type: textarea
  id: code
  attributes:
    label: Unit-Test / Minimal Reproducible Example (MRE)
    description: Please provide a unit-test (preferred) or a minimal complete verifiable
      code example to test/reproduce the bug.
    value: "import ${{package.name]}\n\ndef unit_test():\n    # write a unit-test
      here to reproduce the bug\n    ...\n    assert ...\n"
    render: python
  validations:
    required: true
- type: textarea
  id: log
  attributes:
    label: Error Message
    description: "Please provide the full traceback of the error message.\n"
    render: shell
  validations:
    required: true
