name:  🖥 App 🔔 Request 💥 Breaking Change
description: Request a backward-incompatible change to the API, such as a change in
  the behavior of an existing functionality.
labels:
- 'Type: major-release'
- 'SubType: breaking'
- 'Status: triage'
assignees:
- repodynamics
body:
- type: markdown
  attributes:
    value: "<p align=\"justify\">\n  Thank you for taking the time to report a problem
      in PyPackIT;\n  we greatly appreciate your contribution! ❤️🙏\n</p>\n<h2>Terms
      and Conditions</h2>\n<p align=\"justify\">\n  Before submitting a report, please
      take a moment to review and accept our terms and conditions;\n  they will help
      us process the issue as fast as possible,\n  and not bother you with additional
      questions.\n</p>\n<h3>⛔ Choosing the right form</h3>\n<ul>\n  <li>\n    <p align=\"\
      justify\">\n      Please note that this form is specifically for requesting
      a\n      <b>breaking change</b> in PyPackIT.\n    </p>\n  </li>\n  <li>\n  \
      \  <p align=\"justify\">\n      For other types of issues, such as requesting\n\
      \      <a href=\"${{url.github.issues.new.app_request_enhancement]}\">enhancements</a>,\n\
      \      <a href=\"${{url.github.issues.new.app_request_feature]}\">new features</a>,
      and\n      <a href=\"${{url.github.issues.new.web_request_frontend]}\">changes
      in the website content</a>,\n      or for reporting bugs, please select the
      appropriate form\n      from the <a href=\"${{url.github.issues.template_chooser]}\"\
      >issue template chooser</a>.\n    </p>\n  </li>\n</ul>\n<blockquote>\n  💡 <a
      href=\"https://pypackit.repodynamics.com/help/contact\"><b>Contact us</b></a>\n\
      \  <br>\n  <p align=\"justify\">\n    Can't find the right form or unsure about
      which one to choose?\n    Ask a question and get help in the\n    <a href=\"\
      https://github.com/RepoDynamics/PyPackIT/discussions/new?category=question_issues\"\
      >discussion forum</a>.\n  </p>\n</blockquote>\n<h3>⚠️ Verifying the request</h3>\n
      Before submitting a report, please make sure that you are following our <a href=\"\
      https://pypackit.repodynamics.com/contribute\">Contributing Guidelines</a> to
      verify that: <ol>\n  <li>\n    Your request is in fact for a breaking change,
      and not a new feature or an enhancement.\n  </li>\n  <li>\n    The request has
      not yet been filed by another person.\n  </li>\n</ol>\n<blockquote>\n    💡 <a
      href=\"https://github.com/RepoDynamics/PyPackIT/discussions/new?category=question_issues\"\
      ><b>Open a discussion instead!</b></a>\n    <br>\n    This verification process
      is non-trivial, and can be time-consuming.\n    If you are not a collaborator
      and don't have the time to go through the process,\n    you can always open
      a discussion instead; we will investigate the problem as soon as possible,\n\
      \    and convert the discussion into an issue if the request is valid.\n</blockquote>\n
      <h3>🤝 Code of conduct</h3>\n<p align=\"justify\">\n  Please make sure that you
      are following our\n  <a href=\"https://github.com/RepoDynamics/PyPackIT/blob/main/CODE_OF_CONDUCT.md\"\
      >Code of Conduct</a>,\n  so that we can process the issue as soon as possible.\n\
      </p>\n<h3>✅ Agreements</h3>"
- type: checkboxes
  id: terms
  attributes:
    label: 'To submit an issue, please agree to the following terms and conditions:'
    options:
    - label: I have read the [Contributing Guidelines](https://github.com/RepoDynamics/PyPackIT/blob/main/CONTRIBUTING.md)
        and am following the [Bug Report Guidelines](https://pypackit.repodynamics.com/contribute/feedback/report).
      required: true
    - label: I have read, understood, and agree to follow the [Code of Conduct](https://github.com/RepoDynamics/PyPackIT/blob/main/CODE_OF_CONDUCT.md).
      required: true
- type: markdown
  attributes:
    value: <h3>🧑‍💻 Collaborate</h3>
- type: checkboxes
  attributes:
    label: "Thank you again for filling this feature request.\nIf you are willing
      to collaborate on implementing the new feature, please select the option below.\n"
    options:
    - label: I am willing to work on the issue and submit a pull request.
      required: false
- type: markdown
  attributes:
    value: <br><h2>System and Version Specifications</h2>
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: "Does this request apply to a specific operating system?\nIf so,
      please select the appropriate option.\n"
    multiple: false
    options:
    - Linux
    - Windows
    - macOS
  validations:
    required: false
- type: dropdown
  id: python_version
  attributes:
    label: Python Version
    description: "Does this request apply to a specific Python version?\nIf so, please
      select the appropriate option.\n"
    multiple: false
    options:
    - '3.10'
    - '3.11'
    - '3.12'
  validations:
    required: false
- type: dropdown
  id: package_manager
  attributes:
    label: Package Manager
    description: "Does this request apply to a specific package manager?\nIf so, please
      select the appropriate option.\n"
    multiple: false
    options:
    - conda
    - pip
  validations:
    required: true
- type: markdown
  attributes:
    value: "<br>\n<h2>Modification Request</h2>\n"
- type: dropdown
  id: version
  attributes:
    label: Package Version
    description: "Which version of our software is this request for?\n"
    multiple: false
    options:
    - 0.0.0
  validations:
    required: true
- type: textarea
  id: summary
  attributes:
    label: Summary
    description: "Please provide a brief summary of your request,\nincluding the motivation,
      use case, or problem it solves.\n"
  validations:
    required: true
