# Package Development Configuration
# =================================
#
# Properties
# ----------
# package : object, optional
#    Configurations for package development.
#    ----------
#    Properties
#    ----------
#    dev_config : object, optional
#       Configurations for different package development tools.
#       ----------
#       Properties
#       ----------
#       max_line_length : integer, default: 100
#          Maximum line length for source code files.

dev_config:
  max_line_length: 100
