# isort formatter
# Ref: https://pycqa.github.io/isort/docs/configuration/options.html

[tool.isort]
profile = "black"
line_length = "${{package.dev_config.max_line_length}}"
src_paths = ["${{path.dir.source}}", "${{path.dir.tests}}"]
skip_gitignore = true
lines_before_imports = 2
lines_after_imports = 2
lines_between_sections = 0
verbose = true
color_output = true
only_modified = true
filter_files = true
no_lines_before = ['future', 'stdlib', 'thirdparty', 'firstparty', 'localfolder']
dedup_headings = true
overwrite_in_place = true

[tool.isort.import_headings]
future = 'Futures'
stdlib = 'Standard libraries'
thirdparty = 'Non-standard libraries'
firstparty = 'Self'
