# https://docs.astral.sh/ruff/configuration

[tool.ruff]
required-version = "0.1.5"
cache-dir = "${{ path.dir.local.cache.ruff }}"
output-format = "grouped"
ignore-init-module-imports = true
line-length = 100
show-fixes = true
show-source = true
# https://docs.astral.sh/ruff/rules
select = [
  "F",   # pyflakes
  "E",   # pycodestyle error
  "W",   # pycodestyle warning
  "N",   # pep8-naming
  "D",   # pydocstyle
  "UP",  # pyupgrade
  "YTT", # flake8-2020
  "S",   # flake8-bandit
  "BLE", # flake8-blind-except
  "FBT", # flake8-boolean-trap
  "B",   # flake8-bugbear
  "COM", # flake8-commas
  "C4",  # flake8-comprehensions
  "DTZ", # flake8-datetimez
  "EM",  # flake8-errmsg
  "EXE", # flake8-executable
  "ICN", # flake8-import-conventions
  "PIE", # flake8-pie
  "PT",  # flake8-pytest-style
  "RSE", # flake8-raise
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "TD",  # flake8-todos
  "FIX", # flake8-fixme
  "ERA", # flake8-eradicate
  "PD",  # pandas-vet
  "PGH", # pygrep-hooks
  "PL",  # pylint
  "RUF", # ruff-specific rules
]
ignore = ["PLR1711"]
src = ["${{path.dir.source}}", "${{path.dir.tests}}"]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

[tool.ruff.lint.per-file-ignores]
"${{ path.dir.tests }}/src/**" = ["S101"]

[tool.ruff.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true
suppress-none-returning = true

[tool.ruff.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.flake8-quotes]
docstring-quotes = "single"
multiline-quotes = "single"

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.pylint]
max-args = 10
max-public-methods = 50
max-returns = 10
